version: '3.9'

volumes:
  geekhackvol10_node_modules:
  geekhackvol10_db_data:

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: geekhackvol10_frontend
    tty: true
    volumes:
      - ./frontend:/app/frontend
      # - geekhackvol10_node_modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    command: /bin/sh -c 'npm install && npm run dev'

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: geekhackvol10_backend
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: geekhackvol10_db
    volumes:
      - geekhackvol10_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
